language: cpp
compiler: gcc
before_install:
#- sudo dpkg --add-architecture i386
 - sudo apt-get -qq update
 #- sudo DEBIAN_FRONTEND=noninteractive apt-get -q --yes --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
 - sudo apt-get install -y libxml2-dev libxerces-c-dev python-svn python-lxml astyle cmake xsdcxx default-jre libssl-dev build-essential
 - sudo apt-get install -y libboost-all-dev
 - sudo apt-get install -y gcc-multilib
 - wget --no-check-certificate https://cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
 - tar -xzvf cmake-2.8.12.2.tar.gz 
 - cd cmake-2.8.12.2
 - CC=gcc bash -c './bootstrap'
 - make      
 - sudo make install
 - cd ..
 #- sudo sh -c "echo 'foreign-architecture i386' > /etc/dpkg/dpkg.cfg.d/multiarch"
 # not sure if boost 32 bit is needed for the trial build, but installing this seems to break the compilers
 #- sudo aptitude install -y libboost-all-dev:i386 build-essential:i386
 #- sudo apt-get -f install
 #this is not a permanent link! At some point it may stop working
 - wget --no-check-certificate https://cernbox.cern.ch/index.php/s/nYKgDvAwmSVnMLx/download
 - tar -xzvf download
 - sudo cp -R sdk/ /opt/OpcUaToolkit-1.3.3-evaluation/
script:
 - git clone https://github.com/quasar-team/quasar-validation-ci.git
 #again, the cernbox link is not permanent, be careful
 - wget -O saxon9he.jar --no-check-certificat https://cernbox.cern.ch/index.php/s/FIZm1Ew5CyxLDUd/download
 - mv saxon9he.jar Design/
 - mv quasar-validation-ci/CI/Design.xml Design/
 - mv quasar-validation-ci/CI/config.xml bin/
 - mv quasar-validation-ci/CI/ubuntu_evaluationToolkit.cmake .
 - python quasar.py generate device GreenLED
 - python quasar.py generate device YellowLED
 - python quasar.py generate device RedLED
 - C_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch) && python quasar.py build Release ubuntu_evaluationToolkit.cmake
 #
