language: cpp
compiler: gcc
before_install:
 - sudo apt-get install -y libxml2-dev libxerces-c-dev python-svn python-lxml astyle libboost-all-dev xsdcxx default-jre libssl-dev gcc-multilib g++-multilib
 - wget --no-check-certificate https://cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
 - tar -xzvf cmake-2.8.12.2.tar.gz 
 - cd cmake-2.8.12.2
 - ./bootstrap
 - make      
 - sudo make install
 - cd ..
 
script:
 - cmake -version
 - git clone https://github.com/quasar-team/quasar-validation-ci.git
 - mv quasar-validation-ci/CI/Design.xml Design/
 - python quasar.py generate device GreenLED
 - python quasar.py generate device YellowLED
 - python quasar.py generate device RedLED
 - python quasar.py prepare_build open62541_config.cmake 
 - python quasar.py enable_module open62541-compat open62541-compat-0.2-r1
 - python quasar.py prepare_build open62541_config.cmake 
 - cd open62541-compat/ && ./prepare.sh && cd ..
# - sudo rm Server/src/QuasarServer.cpp
# - mv quasar-validation-ci/CI/open62541CI/QuasarServer.cpp Server/src/
 - mv quasar-validation-ci/CI/config.xml bin/
 - sudo chmod 777 -R *
#set environment vars, then invoke build
 - export BOOST_LIBS="-lboost_thread -lboost_system"
 - python quasar.py build Release open62541_config.cmake
